In [1]:
import numpy as np
from IPython.display import display

In [7]:
num16= np.arange(1, 16 + 1)
num16.reshape(4, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [101]:
num25= np.arange(10, 50, 5)
num25.resize(2, 4) 
print(num25)

[[10 15 20 25]
 [30 35 40 45]]


In [27]:
rand_array = np.random.randint(1, 101, (3, 3))
print('max', rand_array.max())  
print('min', rand_array.min())

max 96
min 10


In [153]:
array = np.arange(0, 21)
print('array[:5]: ' , array[:5])
print('array[::2]: ' , array[::2])
print('array[::-1]: ' , array[::-1])    

array[:5]:  [0 1 2 3 4]
array[::2]:  [ 0  2  4  6  8 10 12 14 16 18 20]
array[::-1]:  [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [105]:
arr = np.random.randint(1, 51, (4, 5))
print('array[1]:' , arr[1])
print('array[3]:' , arr[3])

array[1]: [ 5  9  1  2 35]
array[3]: [16 49 47 39  3]


In [211]:

rand_array = np.random.randint(0, 101, size = 15)
max_index = rand_array.argmax()
min_index = rand_array.argmin()
print(max_index)
print(min_index)


7
8
